# Generated by Django 4.1 on 2022-11-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('department',), 'verbose_name': 'student_department', 'verbose_name_plural': 'student_departments'},
        ),
    ]
