# Generated by Django 4.1 on 2022-11-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
