# Generated by Django 4.1.3 on 2022-11-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_login_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Details',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'student_department', 'verbose_name_plural': 'student_departments'},
        ),
        migrations.RenameField(
            model_name='department',
            old_name='course',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
