# Generated by Django 4.1.3 on 2022-11-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneno', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('material', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department')),
            ],
            options={
                'verbose_name': 'student_details',
                'verbose_name_plural': 'student_details',
                'ordering': ('name',),
            },
        ),
    ]
