# Generated by Django 4.1.3 on 2022-11-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_student_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.course'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.department'),
        ),
    ]
