# Generated by Django 4.1.3 on 2022-11-23 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_student_details_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.course'),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.department'),
        ),
    ]
